### ISSUE TITLE
Image carousel loads behind members section on mobile views

### ISSUE THREAD

**Issue by leiDnedyA** [TheSwiginator/CS-Club-Website#2]
When you open the site in portrait mode and scroll down, the carousel loads behind the members section and when it updates, it moves all of the sections below it down a few pixels. It might be worth it set it to display: none on small screens or find a different way to implement it.

**Comment by TheSwiginator** [comment]
Sorry, I missed this issue ;( but this has since been resolved as a part of patch1.2

Thanks,
Blake M.
